language: c
sudo: required
addons:
  apt:
    sources:
    - avsm
    packages:
    - ocaml
    - opam
    - libffi-dev
    - depqbf

script: bash -ex .travis-ci.sh
matrix:
  include:
    - os: linux
      env: OCAML_VERSION=4.02.0
    - os: linux
      env: OCAML_VERSION=4.02.0
    - os: linux
      env: OCAML_VERSION=4.01.0
    - os: linux
      env: OCAML_VERSION=4.00.1
    - os: linux
      env: OCAML_VERSION=3.12.1
    - os: osx
cache:
  directories:
  - $HOME/.opam